### ISSUE TITLE
[BUG] rsasha256 / rsasha1

### ISSUE THREAD

**Issue by MickL** [node-saml/node-saml#222]
I am not sure if this is a bug or feature request: I succesfully tried node-saml / passport-saml with multiple IdPs. With auth0 however I get the following error:

```
error:1E08010C:DECODER routines::unsupported {}
"Error: error:1E08010C:DECODER routines::unsupported
    at Verify.verify (node:internal/crypto/sig:230:24)
    at RSASHA256.verifySignature (/Users/mick/myapp/node_modules/@node-saml/node-saml/node_modules/xml-crypto/lib/signed-xml.js:140:24)
    at SignedXml.validateSignatureValue (/Users/mick/myapp/node_modules/@node-saml/node-saml/node_modules/xml-crypto/lib/signed-xml.js:460:20)
    at SignedXml.checkSignature (/Users/mick/myapp/node_modules/@node-saml/node-saml/node_modules/xml-crypto/lib/signed-xml.js:397:15)
    at validateXmlSignatureForCert (/Users/mick/myapp/node_modules/@node-saml/node-saml/src/xml.ts:154:14)
    at /Users/mick/myapp/node_modules/@node-saml/node-saml/src/xml.ts:113:39
    at Array.some (<anonymous>)
    at validateSignature (/Users/mick/myapp/node_modules/@node-saml/node-saml/src/xml.ts:112:16)
    at SAML.validatePostResponseAsync (/Users/mick/myapp/node_modules/@node-saml/node-saml/src/saml.ts:691:28)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
```

Within auth0 I only can set the following options:

> signatureAlgorithm: Signature algorithm to sign the SAML Assertion or response. Default is rsa-sha1 and it could be rsa-sha256.

**To Reproduce**

* Create an Application at auth0
* Add addon saml2

**Comment by cjbarth** [comment]
Are you saying that the default signing algorithm should be SHA256 instead of SHA1 and that would fix this issue?

**Comment by MickL** [comment]
I think node-saml cant handle the algorithms used by auth0: `rsasha1` and `rsasha256`

**Comment by cjbarth** [comment]
In that case, please feel free to create a PR to add them.

**Comment by MickL** [comment]
Thanks for the detailed answer! I will dive deeper into this and check if it is a misconfiguration. Will also try to debug the exact problem on monday and give you more feedback.

**Comment by MickL** [comment]
Hello, I tried to run the tests as you mentioned and all 207 tests passed. My env:

```
node: v18.5.0
npm: 8.12.1
openssl: LibreSSL 3.3.6.
os: macOS Ventura 13.0.1
```

I am debugging node-saml to see what the error is causing exactly.

**Comment by cjbarth** [comment]
I've updated the original post to not have a one-liner; for sure that made it harder to see at a glace what was going on.

I'll close this item until you finish your debugging. Feel free to post to re-open.
